# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: eef2b5bc0f0eeb3469648e5537396f76bec8d1214001d84b544bd969fc7a6be074d05b26d2c05662f6b733cd9d29988b30f6e5b832496b8676a3d89aeb949862

test:
  secret_key_base: dc9707670dbce0ea56ae9e39cf1ccba0b2679fb3ab6da9949e609028ad1949c9afa27e0bd3d796b77ec6cd750ddc02250a5b297d95e3c6b93d293797f6b82843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
